version: "3"

services:
  meow-api:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: meow
      MYSQL_USER: meow
      MYSQL_PASSWORD: meow
      MYSQL_ROOT_PASSWORD: root_meow
    ports:
      - "3306:3306"
    volumes:
      - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10